### ISSUE TITLE
[Suggestion] Support for BCLib mods (Crashes when mods are active)

### ISSUE THREAD

**Issue by Gumbofizz** [AmyMialee/black-powder-fabric#5]
Please add support for BCLib , Better Nether and Better End

Game crashes when BCLib and mods are active

**Fabric Version:** 0.13.2
**Minecraft Version:** 1.17.1

**Crash Report:**

[main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.13.2
[main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[main/INFO]: Loading 57 mods:
	- bclib 0.5.6
	- betterend 0.12.5
	- betternether 5.3.14
	- black-powder 1.0.6
	- cloth-basic-math 0.6.0 via cloth-config2
	- cloth-config2 5.3.58
	- fabric 0.46.1+1.17
	- fabric-api-base 0.4.0+cf39a74318 via fabric
	- fabric-api-lookup-api-v1 1.5.0+e821752d18 via fabric
	- fabric-biome-api-v1 3.2.2+cf39a74318 via fabric
	- fabric-blockrenderlayer-v1 1.1.6+cf39a74318 via fabric
	- fabric-command-api-v1 1.1.4+cf39a74318 via fabric
	- fabric-commands-v0 0.2.3+cf39a74318 via fabric
	- fabric-containers-v0 0.1.13+cf39a74318 via fabric
	- fabric-content-registries-v0 0.4.1+3447790d18 via fabric
	- fabric-crash-report-info-v1 0.1.6+cf39a74318 via fabric
	- fabric-dimensions-v1 2.0.15+b556f28c18 via fabric
	- fabric-entity-events-v1 1.4.1+377137cc18 via fabric
	- fabric-events-interaction-v0 0.4.12+e99fbe1218 via fabric
	- fabric-events-lifecycle-v0 0.2.4+cf39a74318 via fabric
	- fabric-game-rule-api-v1 1.0.8+cf39a74318 via fabric
	- fabric-item-api-v1 1.3.0+6617390918 via fabric
	- fabric-item-groups-v0 0.3.2+cf39a74318 via fabric
	- fabric-key-binding-api-v1 1.0.6+2a2bb57318 via fabric
	- fabric-keybindings-v0 0.2.4+cf39a74318 via fabric
	- fabric-lifecycle-events-v1 1.4.6+0392f3a618 via fabric
	- fabric-loot-tables-v1 1.0.5+cf39a74318 via fabric
	- fabric-mining-level-api-v1 1.0.3+cf39a74318 via fabric
	- fabric-mining-levels-v0 0.1.7+cf39a74318 via fabric
	- fabric-models-v0 0.3.1+cf39a74318 via fabric
	- fabric-networking-api-v1 1.0.14+cf39a74318 via fabric
	- fabric-networking-blockentity-v0 0.2.12+cf39a74318 via fabric
	- fabric-networking-v0 0.3.3+cf39a74318 via fabric
	- fabric-object-builder-api-v1 1.11.1+f907116918 via fabric
	- fabric-object-builders-v0 0.7.8+cf39a74318 via fabric
	- fabric-particles-v1 0.2.5+cf39a74318 via fabric
	- fabric-registry-sync-v0 0.8.0+ea29b33318 via fabric
	- fabric-renderer-api-v1 0.4.6+ce16ae5918 via fabric
	- fabric-renderer-indigo 0.4.10+ce16ae5918 via fabric
	- fabric-renderer-registries-v1 3.2.6+cf39a74318 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318 via fabric
	- fabric-rendering-fluids-v1 0.2.1+cf39a74318 via fabric
	- fabric-rendering-v0 1.1.7+cf39a74318 via fabric
	- fabric-rendering-v1 1.10.1+377137cc18 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+591a0f2118 via fabric
	- fabric-resource-loader-v0 0.4.10+f09604ce18 via fabric
	- fabric-screen-api-v1 1.0.5+cf39a74318 via fabric
	- fabric-screen-handler-api-v1 1.1.9+cf39a74318 via fabric
	- fabric-structure-api-v1 1.2.0+48a9ad8918 via fabric
	- fabric-tag-extensions-v0 1.2.3+cf39a74318 via fabric
	- fabric-textures-v0 1.0.7+cf39a74318 via fabric
	- fabric-tool-attribute-api-v1 1.3.3+3b96517518 via fabric
	- fabric-transfer-api-v1 1.5.4+cf39a74318 via fabric
	- fabricloader 0.13.2
	- java 16
	- minecraft 1.17.1
	- multi_item_lib 1.4.0 via black-powder
[main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/ryanc/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[main/INFO]: Compatibility level set to JAVA_16
[main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-api-lookup-api-v1.mixins.json for mod fabric-api-lookup-api-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.13.2.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-api-lookup-api-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.13.2.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-api-lookup-api-v1.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.13.2.jar:?]
	... 3 more

**Comment by AmyMialee** [comment]
There won't be any more updates on 1.17, however if/when the mod comes out for 1.18 it should work immediately, if not make another report. Thanks for reporting though.

**Comment by Gumbofizz** [comment]
Thank you for the notice.
